"use client";
import { FormEvent, useState } from "react";
import { BrainCircuit, Send, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { PageHeading } from "@/components/domain/page-heading";

type Snapshot={clients:number;leads:number;projects:number;tasks:number;overdueTasks:number;invoices:number;outstanding:number};
export function AICommandCenter({snapshot}:{snapshot:Snapshot}){
 const [input,setInput]=useState("");const [answer,setAnswer]=useState("Ask me about your workspace. I can already summarize the real data currently stored here.");
 function respond(q:string){const s=q.toLowerCase();if(s.includes("today")||s.includes("task"))return `You have ${snapshot.tasks} open tasks, including ${snapshot.overdueTasks} overdue. Start with overdue and urgent work first.`;if(s.includes("lead"))return `You currently have ${snapshot.leads} open leads in this workspace. Open Leads to review and update their stages.`;if(s.includes("invoice")||s.includes("money")||s.includes("revenue"))return `You have ${snapshot.invoices} invoices and £${snapshot.outstanding.toLocaleString()} currently not marked paid or void.`;if(s.includes("client"))return `There are ${snapshot.clients} clients in this workspace and ${snapshot.projects} projects connected to your delivery workflow.`;return `Workspace snapshot: ${snapshot.clients} clients, ${snapshot.leads} open leads, ${snapshot.projects} projects and ${snapshot.tasks} open tasks. This assistant is using your live workspace snapshot; full generative AI actions are the next integration step.`;}
 function ask(e:FormEvent){e.preventDefault();const q=input.trim();if(!q)return;setAnswer(respond(q));setInput("")}
 const suggestions=["What do I need to do today?","How many leads are open?","Which invoices need attention?","Summarize my business"];
 return <div className="page-enter space-y-7"><PageHeading eyebrow="Business intelligence" title="AI Command Center" description="Ask questions grounded in your current workspace data." action={<Button onClick={()=>{setInput("");setAnswer("New conversation started. What would you like to know?")}}><Sparkles/>New conversation</Button>}/>
 <section className="overflow-hidden rounded-[24px] border bg-[#1b2b27] p-7 text-white"><div className="flex items-start gap-4"><span className="flex size-11 items-center justify-center rounded-xl bg-white/10"><BrainCircuit/></span><div><p className="text-xs uppercase tracking-[.14em] text-[#9fb0a6]">Live workspace assistant</p><h2 className="mt-2 text-2xl font-semibold">Context → insight → action</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c4d0c9]">{answer}</p></div></div></section>
 <Card><CardHeader className="border-b"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-muted-foreground">Ask your business</p><h2 className="mt-2 text-lg font-semibold">Workspace command</h2></div></CardHeader><CardContent className="pt-6"><div className="mb-4 flex flex-wrap gap-2">{suggestions.map(q=><button key={q} onClick={()=>setAnswer(respond(q))} className="rounded-full border px-3 py-2 text-xs hover:bg-muted">{q}</button>)}</div><form onSubmit={ask} className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about clients, leads, tasks or invoices..." className="min-w-0 flex-1 rounded-xl border px-4 py-3 text-sm outline-none"/><Button type="submit">Ask AI <Send/></Button></form><p className="mt-3 text-[10px] text-muted-foreground">Current version answers from a safe workspace snapshot. It does not modify data or call an external AI model yet.</p></CardContent></Card></div>
}
